// Build script.
//
// 1. macOS: link the Vision framework for the OCR module (not pulled in by
//    Foundation/AppKit).
// 2. FIGlet font bundle: gzip-compress every vendored `.flf` under
//    `assets/figlet-fonts/` into `OUT_DIR/figlet-gz/<index>.gz` and generate
//    `OUT_DIR/figlet_fonts_generated.rs` — a `FONT_BLOBS` table mapping each
//    font name to its embedded compressed bytes (`include_bytes!`). The app
//    inflates a font lazily on first use (see `figlet/fonts.rs`), so the binary
//    carries only ~1 MB of compressed fonts and the 5.7 MB of raw `.flf` never
//    ships nor loads at once.

use std::io::Write;
use std::path::PathBuf;
use std::{env, fs};

fn main() {
    #[cfg(target_os = "macos")]
    println!("cargo:rustc-link-lib=framework=Vision");
    #[cfg(target_os = "macos")]
    println!("cargo:rustc-link-lib=framework=IOBluetooth");

    generate_figlet_bundle();
}

fn generate_figlet_bundle() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let fonts_dir = PathBuf::from(&manifest_dir).join("assets/figlet-fonts");
    println!("cargo:rerun-if-changed={}", fonts_dir.display());

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let gz_dir = out_dir.join("figlet-gz");
    fs::create_dir_all(&gz_dir).expect("create figlet-gz dir");

    // Collect `.flf` files, sorted for a deterministic table.
    let mut entries: Vec<_> = fs::read_dir(&fonts_dir)
        .unwrap_or_else(|e| panic!("read {}: {e}", fonts_dir.display()))
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|x| x == "flf"))
        .collect();
    entries.sort();

    let mut table = String::from(
        "// Generated by build.rs from assets/figlet-fonts/*.flf — do not edit.\n\
         pub static FONT_BLOBS: &[(&str, &[u8])] = &[\n",
    );
    for (i, path) in entries.iter().enumerate() {
        let name = path.file_stem().unwrap().to_string_lossy().to_string();
        let raw = fs::read(path).expect("read .flf");

        let gz_path = gz_dir.join(format!("{i}.gz"));
        let mut enc =
            flate2::write::GzEncoder::new(Vec::new(), flate2::Compression::best());
        enc.write_all(&raw).expect("gzip write");
        let compressed = enc.finish().expect("gzip finish");
        fs::write(&gz_path, &compressed).expect("write .gz");

        // A `.flf` font name only contains printable ASCII (incl. `'`/`!`);
        // `escape_default` keeps the generated string literal valid regardless.
        table.push_str(&format!(
            "    (\"{}\", include_bytes!(concat!(env!(\"OUT_DIR\"), \"/figlet-gz/{i}.gz\"))),\n",
            name.escape_default(),
        ));
    }
    table.push_str("];\n");

    fs::write(out_dir.join("figlet_fonts_generated.rs"), table).expect("write generated table");
}
