#!/usr/bin/env node
// gen-docs.mjs — the CommandDoc registry is the single source of truth for the
// README search-bar-command matrix. This script renders that matrix from
// core/frontend/src/lib/commandDocs.ts and injects it between the
// `<!-- COMMANDS:START -->` / `<!-- COMMANDS:END -->` markers in README.md
// (English `tagline`) and README.de.md (`tagline_de` ?? `tagline`).
//
//   node scripts/gen-docs.mjs           # rewrite the marked blocks
//   node scripts/gen-docs.mjs --check   # verify they're in sync (CI gate)
//
// The --check mode also verifies every doc's see_also points at a real file —
// the filesystem half of the completeness gate the (node-free) vitest test
// can't do. It exits non-zero on drift or a missing doc, with an actionable
// message. Idempotent: re-running after a write is a no-op.

import { createRequire } from "node:module";
import { existsSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const CHECK = process.argv.includes("--check");
const START = "<!-- COMMANDS:START -->";
const END = "<!-- COMMANDS:END -->";

// ── Load the registry (TS → JS via esbuild; the file has zero imports) ───────
// Transpile to an ESM temp module and dynamic-import it — no `new Function`
// eval, and the input is the repo's own version-controlled registry file.
async function loadDocs() {
  const require = createRequire(import.meta.url);
  // esbuild ships as a transitive dep (vite). Resolve it from the pnpm store
  // without hard-coding a version.
  let esbuild;
  try {
    esbuild = require("esbuild");
  } catch {
    const pnpm = join(ROOT, "node_modules/.pnpm");
    const dir = readdirSync(pnpm).find((d) => /^esbuild@/.test(d));
    if (!dir) {
      console.error("gen-docs: esbuild not found (needed to read the TS registry). Run `pnpm install`.");
      process.exit(2);
    }
    esbuild = require(join(pnpm, dir, "node_modules/esbuild"));
  }
  const src = readFileSync(join(ROOT, "core/frontend/src/lib/commandDocs.ts"), "utf8");
  const { code } = esbuild.transformSync(src, { loader: "ts", format: "esm" });
  const dir = mkdtempSync(join(tmpdir(), "ir-gendocs-"));
  const modPath = join(dir, "commandDocs.mjs");
  try {
    writeFileSync(modPath, code);
    const mod = await import(pathToFileURL(modPath).href);
    return mod.COMMAND_DOCS;
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

// ── Render ───────────────────────────────────────────────────────────────────
const esc = (s) => s.replace(/\|/g, "\\|");

// Numeric semver key so `0.84.234` sorts AFTER `0.84.72` (not lexically).
const versionKey = (v) => String(v).split(".").map((n) => parseInt(n, 10) || 0);
function byVersionThenName(a, b) {
  const va = versionKey(a.version_added);
  const vb = versionKey(b.version_added);
  for (let i = 0; i < Math.max(va.length, vb.length); i++) {
    const d = (va[i] || 0) - (vb[i] || 0);
    if (d) return d;
  }
  return a.command.localeCompare(b.command);
}

function renderMatrix(docs, german) {
  // The command matrix is sorted by version (oldest → newest) so the table
  // reads as the tool's evolution; ties break by command name. (The Features
  // tab keeps the registry/category order — this only affects the README.)
  const rows = [...docs].sort(byVersionThenName).map((d) => {
    const aliases =
      d.aliases.length > 0
        ? ` <sub>(alias: ${d.aliases.map((a) => `\`${a}\``).join(", ")})</sub>`
        : "";
    const tagline = german ? (d.tagline_de ?? d.tagline) : d.tagline;
    // Command cell = the primary keyword; the full grammar lives in the inline
    // `?` help, not the matrix (keeps multi-form commands like tr/g compact).
    return `| \`${esc(d.command)}\`${aliases} | v${d.version_added} | ${esc(tagline)} |`;
  });
  const head = german
    ? ["| Befehl | Seit | Was er tut |", "|--------|------|------------|"]
    : ["| Command | Since | What it does |", "|---------|-------|--------------|"];
  return [
    START,
    "<!-- Generated by scripts/gen-docs.mjs from core/frontend/src/lib/commandDocs.ts — do not edit by hand. -->",
    "",
    ...head,
    ...rows,
    "",
    END,
  ].join("\n");
}

function replaceBlock(text, block, file) {
  const s = text.indexOf(START);
  const e = text.indexOf(END);
  if (s === -1 || e === -1 || e < s) {
    console.error(`gen-docs: ${file} is missing the ${START} … ${END} markers.`);
    process.exit(2);
  }
  return text.slice(0, s) + block + text.slice(e + END.length);
}

// ── see_also existence (the fs half of the completeness gate) ────────────────
function checkSeeAlso(docs) {
  const missing = [];
  for (const d of docs) {
    if (d.see_also && !existsSync(join(ROOT, d.see_also))) missing.push(`${d.command} → ${d.see_also}`);
  }
  return missing;
}

// ── Main ─────────────────────────────────────────────────────────────────────
const docs = await loadDocs();

const badSeeAlso = checkSeeAlso(docs);
if (badSeeAlso.length > 0) {
  console.error("gen-docs: see_also targets do not exist:\n  " + badSeeAlso.join("\n  "));
  process.exit(1);
}

const targets = [
  { file: "README.md", german: false },
  { file: "README.de.md", german: true },
];

let drift = false;
for (const { file, german } of targets) {
  const path = join(ROOT, file);
  const text = readFileSync(path, "utf8");
  const block = renderMatrix(docs, german);
  const next = replaceBlock(text, block, file);
  if (CHECK) {
    if (next !== text) {
      drift = true;
      console.error(`gen-docs: ${file} command matrix is OUT OF SYNC with the registry.`);
    }
  } else if (next !== text) {
    writeFileSync(path, next);
    console.log(`gen-docs: updated ${file} (${docs.length} commands).`);
  } else {
    console.log(`gen-docs: ${file} already up to date.`);
  }
}

if (CHECK && drift) {
  console.error("\nRun `node scripts/gen-docs.mjs` and commit the result.");
  process.exit(1);
}
if (CHECK) console.log(`gen-docs: in sync (${docs.length} commands, see_also OK).`);
