// WebMCP tools: lets an AI agent in the browser ask this page for facts and actions directly instead of
// scraping it (https://developer.chrome.com/docs/ai/webmcp). Only registered where the browser offers
// `modelContext`; everywhere else this file does nothing. All data comes from the same places the page
// uses — latest.json and changelog.md on this origin — so tools and page can never disagree.
(function () {
  'use strict';

  var mc = (typeof document !== 'undefined' && document.modelContext) ||
    (typeof navigator !== 'undefined' && navigator.modelContext);
  if (!mc || typeof mc.registerTool !== 'function') return;

  // Facts from site.json (generated by build.py).
  var FACTS = {
    "name": "Inspector Rust",
    "summary": "Free, open-source (MIT) desktop utility for macOS, Windows and Linux. Ctrl+Space opens a popup with a searchable, encrypted clipboard history, a text expander and 66 search-bar commands: calculator and unit converter, translation, weather, screenshots with OCR and annotation, screen recording, colour picker, system and audio tools. Data stays in a local SQLite database with AES-256-GCM encryption at rest; there is no account and no telemetry.",
    "requirements": {
      "macos": "macOS 11+ · Apple silicon",
      "windows": "Windows 10/11 · x64 · installer",
      "windows-exe": "Windows 10/11 · x64 · no install",
      "linux-deb": "Ubuntu 24.04+ / Debian 13 · x86-64",
      "linux-appimage": "Linux x86-64"
    },
    "platforms": [
      "macOS",
      "Windows",
      "Linux"
    ],
    "features": [
      "Searchable clipboard history for text, images, files and rich text, with pins and notes",
      "Text expander with abbreviations, hotkeys and placeholders such as date, clipboard and cursor",
      "66 search-bar commands, each with built-in help (type a command followed by ?)",
      "Calculator, unit and base converter, live translation",
      "Screenshots with annotation editor, OCR of any screen region, screen recording to MP4",
      "Colour picker with magnifier, QR codes, password generator, 2FA codes",
      "System tools: brightness, audio output, disk usage, cache clean-up, system stats",
      "Weather, world clock, calendar, song recognition, Philips Hue control",
      "Local SQLite database, sensitive fields encrypted with AES-256-GCM",
      "No account, no telemetry; network only for commands that need it"
    ],
    "limits": [
      "macOS builds are Apple silicon only and not notarized; the first launch needs one Terminal command.",
      "Some features are macOS-only (for example the network monitor and touchpad gestures).",
      "Linux: global shortcuts may need to be bound in the desktop settings under Wayland."
    ],
    "targets": [
      "macos",
      "windows",
      "windows-exe",
      "linux-deb",
      "linux-appimage"
    ],
    "signing": [],
    "links": {
      "page": "https://inspector-rust.celox.io/",
      "download": "https://inspector-rust.celox.io/download",
      "latest": "https://inspector-rust.celox.io/latest.json",
      "markdown": "https://inspector-rust.celox.io/index.md",
      "changelog": "https://inspector-rust.celox.io/changelog.md",
      "skill": "https://inspector-rust.celox.io/skills/get-inspector-rust/SKILL.md",
      "source": "https://github.com/pepperonas/inspector-rust",
      "licence": "https://github.com/pepperonas/inspector-rust/blob/main/LICENSE"
    }
  };
  var SITE = FACTS.links.page.replace(/\/$/, '');
  var LANGS = ['en', 'de', 'es', 'it', 'fr'];

  function latest(signal) {
    return fetch('/latest.json', { cache: 'no-cache', signal: signal }).then(function (r) {
      if (!r.ok) throw new Error('latest.json: HTTP ' + r.status);
      return r.json();
    });
  }
  function json(v) { return JSON.stringify(v, null, 2); }
  var READ = { readOnlyHint: true };

  var tools = [
    {
      name: 'get_app_facts',
      description: 'What Inspector Rust is: a one-paragraph summary, requirements, supported platforms, ' +
        'features, limits and the important links (download, source, changelog, licence).',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
      annotations: READ,
      execute: function () { return Promise.resolve(json(FACTS)); }
    },
    {
      name: 'get_latest_release',
      description: 'The newest release of Inspector Rust: version, publication date, release notes URL ' +
        'and every file with its download URL, size in bytes and SHA-256.',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
      annotations: READ,
      execute: function (_input, opts) {
        return latest(opts && opts.signal).then(function (d) {
          return json({ version: d.version, published: d.published, notes: d.notes, assets: d.assets ||
            [{ target: FACTS.targets[0], name: d.name, url: d.url, size: d.size, sha256: d.sha256 }] });
        });
      }
    },
    {
      name: 'get_download_url',
      description: 'The direct download URL of the newest Inspector Rust file for a platform (macos, windows, windows-exe, linux-deb, linux-appimage), plus ' +
        'the stable link that always redirects to the newest file.',
      inputSchema: {
        type: 'object',
        properties: { platform: { type: 'string', enum: FACTS.targets, description: 'Target platform; default: ' + FACTS.targets[0] + '.' } },
        additionalProperties: false
      },
      annotations: READ,
      execute: function (input, opts) {
        return latest(opts && opts.signal).then(function (d) {
          var assets = d.assets || [{ target: FACTS.targets[0], name: d.name, url: d.url, size: d.size }];
          var want = (input && input.platform) || assets[0].target;
          var a = assets.filter(function (x) { return x.target === want; })[0] || assets[0];
          return json({ version: d.version, platform: a.target, file: a.name, url: a.url, size: a.size,
            stable_link: SITE + '/download/' + a.target });
        });
      }
    },
    {
      name: 'get_checksums',
      description: 'How to verify a downloaded Inspector Rust file: the SHA-256 of every file of the newest release ' +
        'and the fixed signing facts.',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
      annotations: READ,
      execute: function (_input, opts) {
        return latest(opts && opts.signal).then(function (d) {
          var assets = d.assets || [{ name: d.name, sha256: d.sha256 }];
          return json({ version: d.version,
            files: assets.map(function (a) { return { name: a.name, sha256: a.sha256 }; }),
            signing: FACTS.signing });
        });
      }
    },
    {
      name: 'get_changelog',
      description: 'The most recent entries of the Inspector Rust changelog as Markdown.',
      inputSchema: {
        type: 'object',
        properties: { versions: { type: 'integer', minimum: 1, maximum: 10, description: 'How many versions (default 3).' } },
        additionalProperties: false
      },
      annotations: READ,
      execute: function (input, opts) {
        var n = Math.min(10, Math.max(1, (input && input.versions) || 3));
        return fetch('/changelog.md', { cache: 'no-cache', signal: opts && opts.signal }).then(function (r) {
          if (!r.ok) throw new Error('changelog.md: HTTP ' + r.status);
          return r.text();
        }).then(function (md) {
          var parts = md.split(/\n(?=## \[)/).slice(1).filter(function (s) { return !/^## \[Unreleased\]\s*$/.test(s.trim()); });
          return parts.slice(0, n).join('\n').trim();
        });
      }
    },
    {
      name: 'set_page_language',
      description: 'Show this page in another language (English, German, Spanish, Italian or French).',
      inputSchema: {
        type: 'object',
        properties: { language: { type: 'string', enum: LANGS, description: 'ISO 639-1 code.' } },
        required: ['language'],
        additionalProperties: false
      },
      annotations: { readOnlyHint: false },
      execute: function (input) {
        if (LANGS.indexOf(input.language) < 0) throw new Error('unsupported language: ' + input.language);
        if (typeof window.SITE_setLanguage === 'function') window.SITE_setLanguage(input.language);
        return Promise.resolve('Page language set to ' + input.language + '.');
      }
    }
  ];

  tools.forEach(function (t) {
    try { mc.registerTool(t); } catch (e) { /* a browser with an older WebMCP shape: skip that tool */ }
  });
})();
