// Auto-generated from VPS DB (nicetobenice_db) — top 100 openers ranked by
// martinpaush@gmail.com's ratings (DESC) + favourites, with avg_rating as
// the global tiebreaker. Regenerate via the SQL in CLAUDE.md when the
// upstream list shifts.

export const TOP_OPENERS: ReadonlyArray<string> = 
[
  "Wenn du ein Mann wärst, würdest du dann auf Ziegen oder auf Schafe stehen?",
  "Ich bin zwar nicht Glumanda, aber bei dir brennt trotzdem mein Schwanz.",
  "Würdest du Socken tragen, wenn du keine Füße hättest? Warum trägst du dann einen BH?",
  "Soll ich dir meine Pokémon-Karten zeigen?",
  "Darf ich kurz dein Handy haben? Ich muss daheim Bescheid sagen, dass ich heute bei dir schlafe.",
  "Was hältst du davon, wenn wir uns mal auf eine Tafel Schokolade treffen?",
  "Kaufst du mir ein Eis, oder soll ich dich lecken?",
  "Würdest du für 200 € mit mir schlafen? Schade, ich hätte das Geld gut gebrauchen können.",
  "Ich esse gerne kleine Hundewelpen. Was hast du für Hobbys?",
  "Eigentlich bin ich kein Typ für eine Nacht, aber für dich würde ich eine Ausnahme machen.",
  "Ich lecke besser als deine Katze.",
  "Ich habe mir ein neues Bett gekauft. Können wir es mal auf Stabilität testen? Ist echt wichtig!",
  "Dein Gesicht auf einer Briefmarke? Die Post geht pleite!",
  "Merke dir meinen Namen, denn du wirst ihn die ganze Nacht schreien.",
  "Du bist zwar nicht mein Typ, aber ich bin ja tolerant.",
  "Soll ich dir mal einen Zaubertrick zeigen, der funktioniert? Ich ficke dich, und dann verschwindest du.",
  "Kaufst du mir eine Zuckerwatte?",
  "Hey, ich hab Sackratten. Wenn du Tripper hast, können wir tauschen.",
  "Kommst du mit in den Wald? Ich habe da eine Tafel Schokolade versteckt.",
  "Hast du 3 Stunden Zeit und 17 cm Platz?",
  "Ich bin vom ADAC. Darf ich dich abschleppen?",
  "Ich bin der Sohn von David Copperfield. Darf ich dir mal einen schönen Orgasmus zaubern?",
  "Ich bin vom TÜV. Darf ich mal deine Hupen testen?",
  "Kaufst du mir ein Eis? Du darfst auch an mir lecken.",
  "Du bist die erste Frau, die ich anspreche, ich bin auch ziemlich nervös. Willst du ficken?",
  "Du hast Glück! Ich bin wieder Single!",
  "Bevor ich dich vernasche, Puppe, ess ich eine Nudelsuppe.",
  "Lass uns was machen, was sich auf Stricken reimt.",
  "Ich traue mich heute Abend nicht alleine ins Bett. Kommst du mit?",
  "Wenn es dich zu kaufen gäbe, würde ich dich klauen, denn so etwas Wertvolles wie dich kann ich mir leider nicht leisten.",
  "Entschuldige, ich will dich nicht dumm anmachen, aber ich hätte auch nichts dagegen, wenn du es tust.",
  "*Anrempeln* Oh, entschuldige, ich bin nicht mit den richtigen Bremsen für deine Kurven ausgestattet.",
  "Rosen sind rot, Veilchen sind blau, ich bin beim Flirten schüchtern, und du hast sehr schöne Brüste.",
  "Sag mal, bist du homosexuell? – Gut, ich auch nicht, lass uns Sex haben.",
  "Wollen wir morgen zusammen frühstücken?",
  "Na, Schnitte, schon belegt?",
  "Ich habe gerade meine Termine gecheckt, bin mir ziemlich sicher, dass ich dich bis heute Mittag noch schwängern kann.",
  "Hey, Baby, hast du Wasser in den Beinen, oder warum schlägt die ganze Zeit meine Wünschelrute aus?",
  "Ene, mene, miste… Ich finger nicht, ich fiste.",
  "Wenn du mir ein Haus und einen Porsche kaufst, gehöre ich dir.",
  "Hallo, ich bin Meister Proper. Darf ich mal dein Becken schrubben?",
  "Entschuldige, kannst du mir sagen, ob dieses Taschentuch nach Chloroform riecht?",
  "Küss mich, ich bin ein verzauberter Kaffeevollautomat. Siehst du, da ist auch schon die Latte.",
  "Wo finde ich hier den nächsten Swingerclub?",
  "Soll ich dir einen Trick zeigen? Ich verschwinde morgen früh ohne Frühstück.",
  "Hast du in Zucker gebadet, oder warum bist du so süß?",
  "Ich bin Organhändler. Kann ich dein Herz haben?",
  "Ich bin wie ein guter Wein, ich mache dich erst glücklich, und dann liegst du flach.",
  "Ich würde dich gerne mal horizontal kennenlernen.",
  "Was ist das Verrückteste, das du je gemacht hast?",
  "Wenn dein Leben ein Film wäre, wer würde dich spielen?",
  "Wenn du morgen überall auf der Welt aufwachen könntest, wo wäre das?",
  "Was ist deine ungewöhnlichste Fähigkeit, von der niemand weiß?",
  "Welche Regel würdest du gerne brechen, traust dich aber nicht?",
  "Was war dein letztes Abenteuer?",
  "Was würdest du tun, wenn du wüsstest, du kannst nicht scheitern?",
  "Ich sollte dich eigentlich nicht ansprechen - du siehst nach Herzschmerz aus.",
  "Du bist genau mein Beuteschema.",
  "Ich bin kein Wetterfrosch, aber heute Nacht kannst du mit ein paar Zentimetern rechnen.",
  "Ich bin kein Klempner, aber lass mich mal an deine Rohre.",
  "Meine Matratze hat heute Geburtstag. Kommst du zur Party?",
  "Ich bin kein Zahnarzt, aber ich könnte dir ein Bohrerlebnis verschaffen.",
  "Ich bin kein Gärtner, aber ich kann dir einen Stängel zeigen, der dich interessieren dürfte.",
  "Kommst du mit zu mir?",
  "Hey, Trouble.",
  "Hey, zukünftige Affäre.",
  "Cola oder Pepsi?",
  "Heute Abend will dieser Han nicht Solo fliegen.",
  "Du siehst so gut aus, ich hab meinen Anmachspruch vergessen.",
  "Wenn Blicke ausziehen könnten, wärst du gerade in Schwierigkeiten.",
  "Ich hab das Gefühl, wir würden uns sehr gut streiten.",
  "Ich bin gefährlich für deine Schlafqualität. Nur damit du gewarnt bist.",
  "Wenn wir ein Abenteuer planen würden – wohin ginge die Reise?",
  "Ich hab gehört, die besten Nächte fangen mit einem frechen Spruch an. Bitteschön.",
  "Ich bin kein Zahnarzt, aber ich würde gerne mal sehen, wie weit du deinen Mund aufmachen kannst.",
  "Ich hab uns schon mal für eine Paartherapie angemeldet. Man kann nie zu früh anfangen, an einer kaputten Beziehung zu arbeiten.",
  "Ich hab uns gerade ein Haus am See gekauft. Du musst nur noch den Kredit unterschreiben. Teamwork!",
  "Später bei mir?",
  "Sei brav. Wir gehen gleich.",
  "Lust auf Atemnot?",
  "Katsche Batsche",
  "Gleich fesseln?",
  "Zimmernummer?",
  "Zimmer 69?",
  "Heute ohne?",
  "Du siehst aus wie meine Schweste… Aber küsst du auch so gut?",
  "*Anspringen*",
  "Du bist so heiß! Kein Wunder, dass die Gletscher schmelzen.",
  "Sind deine Brüste echt? Darf ich mal anfassen?",
  "Bist du in Hundescheiße getreten, oder riechst du immer so?",
  "Wie schmeckt eigentlich Sperma? Meine Exfreundin sagte immer, es schmeckt überhaupt nicht.",
  "Hi, du gefällst mir! Lass uns mal bei WOW in Molten Core den Magmadar bashen.",
  "Wenn ich dein Gesicht so sehe, gefällt mir mein Arsch wieder.",
  "Kennst du dich hier aus? Ich suche hier gerade was. Kannst du mir den Weg zu deinem Herzen zeigen?",
  "Du bist so egoistisch! Du hast deinen Körper dein ganzes Leben. Ich will ihn nur für eine Nacht.",
  "Auf welche Anmache würdest du am positivsten reagieren?",
  "Mit einem großen Penis hat man auch eine große Verantwortung.",
  "Ich bin Wissenschaftler von der NASA, morgen um 13 Uhr geht die Welt unter. Wollen wir nochmal Sex haben?",
  "Was hast du denn da für ein krasses XYZ? Bist du ein Hipster?!",
  "Ich bin Geheimagent, darf ich eine Woche bei dir schlafen?"
]
;
